### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pmonks**
Also adds a `deps.edn` containing those dependencies, to better support tools.deps / Clojure CLI users.

Note: this PR has been tested, but only with the single, unauthenticated, simple RSS feed that my app is using, in RSS 2.0 & Atom 1.0 format.  More comprehensive testing is advisable!

### CODE REVIEW

**Comment by igrishaev** [comment]
@pmonks thank you, I'll take a closer look the next morning.

**Comment by pmonks** [comment]
Awesome!  No hurry from my end btw.

**Comment by igrishaev** [comment]
Version [0.2.0] is out, you're welcome to use it. Thank you for contributing!

**Comment by pmonks** [comment]
@igrishaev and thank you for authoring this library and being responsive to "fly by" PRs!  😉

**Pull request merged**
